version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: gug007
      POSTGRES_DB: topmek
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  client:
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      SERVER_HOST: "server:4010"
  server:
    build: ./server
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://gug007:password@db/topmek
      PORT: 5432
    ports:
      - 4010:4010
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #  - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    #command: /bin/bash -c "envsubst '$${STATIC_URL}' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80
