version: "3.7"

services:
  client:
    volumes:
      - ./client:/usr/src/app
  server:
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/public:/usr/src/app/public
    entrypoint: ./wait-for-it.sh db:5432 -- npm start
