version: "3.7"

services:
  client:
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/usr/src/app
  server:
    environment:
      NODE_ENV: development
    volumes:
      - ./server/src:/usr/src/app/src
    entrypoint: ./wait-for-it.sh db:5432 -- npm start
